name: extension_cs
description: "Comprehensive Flutter extensions package for Color, DateTime, Navigator, Size, Theme, and Widget manipulations with responsive design support."
version: 0.0.1
homepage: https://github.com/Cagdassrgl/extension_cs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

